version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension


  prometheus:
    container_name: prometheus123
    image: prom/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana123
    image: grafana/grafana
    ports:
      - "3000:3000"

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  spring-boot-app1:
    image: jimmccarthy/sample-spring-boot-docker
    ports:
      - "8081:8080" # Adjust ports as needed
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=spring-boot-app1
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_OTLP_ENDPOINT=localhost:4318
      - OTEL_EXPORTER_OTLP_SPAN_TIMEOUT=5s
      - OTEL_EXPORTER_OTLP_METRICS_TIMEOUT=5s
    depends_on:
      - otel-collector